const cfg=window.TRACKER_CONFIG||{};let db,user,profile,profiles=[];const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const clean=html=>{const t=document.createElement('template');t.innerHTML=html;[...t.content.querySelectorAll('*')].forEach(n=>{if(!['B','STRONG','I','EM','BR','P','DIV','SPAN','MARK','UL','OL','LI'].includes(n.tagName))n.replaceWith(...n.childNodes);else [...n.attributes].forEach(a=>{if(a.name!=='style'||!/^(color|background-color):/.test(a.value))n.removeAttribute(a.name)})});return t.innerHTML};
const toast=m=>{const e=$('#toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2400)};
const today=()=>new Date().toISOString().slice(0,10);const fmt=d=>new Intl.DateTimeFormat('es',{dateStyle:'medium',timeStyle:d.includes('T')?'short':undefined}).format(new Date(d));
function boot(){if(!cfg.supabaseUrl||cfg.supabaseUrl.includes('YOUR_')){$('#auth-view .micro').innerHTML='Configuración pendiente. Sigue README.md.<br>配置尚未完成，请查看 README.md。';return}db=supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);db.auth.getSession().then(({data})=>session(data.session));db.auth.onAuthStateChange((_e,s)=>setTimeout(()=>session(s),0))}
async function session(s){if(!s){user=null;$('#auth-view').classList.remove('hidden');$('#app-view').classList.add('hidden');return}user=s.user;let{data:p}=await db.from('profiles').select('*').eq('id',user.id).single();if(!p){toast('Perfil no autorizado · 未授权用户');await db.auth.signOut();return}profile=p;({data:profiles=[]}=await db.from('profiles').select('*').order('display_name'));$('#auth-view').classList.add('hidden');$('#app-view').classList.remove('hidden');$('#user-name').textContent=p.display_name;$('#learning-label').textContent=p.learning_language==='es'?'Aprende español · 学西语':'Aprende chino · 学中文';$('#avatar').textContent=p.display_name[0].toUpperCase();$('#date-line').textContent=new Intl.DateTimeFormat('es',{weekday:'long',day:'numeric',month:'long'}).format(new Date());$('#greeting').textContent=`Hola, ${p.display_name} · 你好，${p.display_name}`;await Promise.all([loadTasks(today(),'#today-tasks'),loadWords(),loadResources(),loadStats()])}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const{error}=await db.auth.signInWithPassword({email:$('#email').value,password:$('#password').value});if(error)toast('Datos incorrectos · 邮箱或密码不正确')});$('#logout').onclick=()=>db.auth.signOut();
$('#nav').onclick=e=>{const b=e.target.closest('[data-view]');if(!b)return;$$('#nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(x=>x.classList.remove('active'));$(`#view-${b.dataset.view}`).classList.add('active');$('.sidebar').classList.remove('open');if(b.dataset.view==='history')loadTasks($('#history-date').value||today(),'#history-tasks')};$('#menu').onclick=()=>$('.sidebar').classList.toggle('open');
$('#new-task').onclick=()=>$('#task-composer').classList.toggle('hidden');$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).classList.add('hidden'));$$('.toolbar button').forEach(b=>b.onclick=()=>document.execCommand(b.dataset.cmd,false,b.dataset.val||null));
['task-audio','task-image'].forEach(id=>$('#'+id).onchange=()=>$('#file-summary').textContent=[$('#task-audio').files[0]?.name,$('#task-image').files[0]?.name].filter(Boolean).join(' · '));
async function upload(file,folder){if(!file)return null;if(file.size>12*1024*1024)throw Error('12MB');const path=`${user.id}/${folder}/${crypto.randomUUID()}-${file.name.replace(/[^\w.()-]/g,'_')}`;const{error}=await db.storage.from('learning-media').upload(path,file);if(error)throw error;return path}
$('#save-task').onclick=async()=>{const title=$('#task-title').value.trim(),body=clean($('#task-text').innerHTML);if(!title&&!body)return toast('Añade texto o título · 请添加文字或标题');$('#save-task').disabled=true;try{const[audio_path,image_path]=await Promise.all([upload($('#task-audio').files[0],'audio'),upload($('#task-image').files[0],'images')]);const{data,error}=await db.from('tasks').insert({owner_id:user.id,title:title||'Práctica · 练习',body,language:$('#task-language').value,task_date:today(),audio_path,image_path}).select().single();if(error)throw error;resetTask();await loadTasks(today(),'#today-tasks');if(cfg.aiEnabled)runAI(data.id)}catch(e){toast(e.message==='12MB'?'Máximo 12 MB · 最大12MB':e.message)}finally{$('#save-task').disabled=false}};
function resetTask(){$('#task-title').value='';$('#task-text').innerHTML='';$('#task-audio').value='';$('#task-image').value='';$('#file-summary').textContent='';$('#task-composer').classList.add('hidden')}
async function signed(path){if(!path)return null;const{data}=await db.storage.from('learning-media').createSignedUrl(path,3600);return data?.signedUrl}
async function loadTasks(date,target){const box=$(target);box.innerHTML='<p>Cargando… · 加载中…</p>';const{data,error}=await db.from('tasks').select('*,comments(*)').eq('task_date',date).order('created_at',{ascending:false});if(error){box.innerHTML=`<p>${esc(error.message)}</p>`;return}box.innerHTML='';if(!data.length)box.innerHTML='<div class="card"><p>Todavía no hay práctica. · 今天还没有练习。</p></div>';for(const t of data)box.append(await taskCard(t))}
async function taskCard(t){const n=$('#task-template').content.cloneNode(true),card=n.querySelector('.task'),owner=profiles.find(p=>p.id===t.owner_id);card.dataset.id=t.id;n.querySelector('.author').textContent=owner?.display_name||'—';n.querySelector('time').textContent=fmt(t.created_at);n.querySelector('.lang').textContent=t.language==='es'?'Español · 西班牙语':'中文 · Chino';n.querySelector('h3').textContent=t.title;n.querySelector('.task-body').innerHTML=clean(t.body);const att=n.querySelector('.attachments');if(t.image_path){const img=document.createElement('img');img.src=await signed(t.image_path);img.alt='Imagen de la práctica · 练习图片';att.append(img)}if(t.audio_path){const a=document.createElement('audio');a.controls=true;a.src=await signed(t.audio_path);att.append(a)}if(t.ai_feedback){n.querySelector('.ai-box').classList.remove('hidden');n.querySelector('.ai-box div').textContent=t.ai_feedback}const comments=n.querySelector('.comments'),list=n.querySelector('.comment-list');renderComments(list,t.comments||[]);n.querySelector('.comments-toggle').onclick=()=>comments.classList.toggle('hidden');n.querySelector('.comments-toggle span').textContent=`(${t.comments?.length||0})`;n.querySelector('.comment-form').onsubmit=async e=>{e.preventDefault();const inp=e.target.querySelector('input'),{error}=await db.from('comments').insert({task_id:t.id,owner_id:user.id,body:inp.value.trim()});if(error)return toast(error.message);inp.value='';loadTasks(t.task_date,t.task_date===today()?'#today-tasks':'#history-tasks')};const del=n.querySelector('.delete-task');if(t.owner_id===user.id){del.classList.remove('hidden');del.onclick=async()=>{if(!confirm('¿Eliminar? · 确定删除？'))return;await db.from('tasks').delete().eq('id',t.id);loadTasks(t.task_date,t.task_date===today()?'#today-tasks':'#history-tasks')}}const ai=n.querySelector('.ai-action');ai.classList.toggle('hidden',!cfg.aiEnabled||t.owner_id!==user.id);ai.onclick=()=>runAI(t.id);return n}
function renderComments(box,items){box.innerHTML=items.sort((a,b)=>a.created_at.localeCompare(b.created_at)).map(c=>{const p=profiles.find(x=>x.id===c.owner_id);return `<div class="comment"><strong>${esc(p?.display_name||'—')}</strong><small>${fmt(c.created_at)}</small><div>${esc(c.body)}</div></div>`}).join('')}
async function runAI(id){toast('La IA está revisando… · AI 正在检查…');const{data,error}=await db.functions.invoke('ai-feedback',{body:{task_id:id}});if(error)return toast('No se pudo revisar · 暂时无法检查');await db.from('tasks').update({ai_feedback:data.feedback,transcript:data.transcript||null}).eq('id',id);await loadTasks(today(),'#today-tasks');toast('Revisión lista · 修改建议已完成')}
$('#history-date').value=today();$('#history-date').onchange=e=>loadTasks(e.target.value,'#history-tasks');
$('#new-word').onclick=()=>$('#word-form').classList.toggle('hidden');$('#save-word').onclick=async()=>{const term=$('#word-term').value.trim(),lang=$('#word-language').value,pinyin=$('#word-pinyin').value.trim();if(!term)return toast('Añade una palabra · 请添加单词');if(lang==='zh'&&!pinyin)return toast('El pinyin es obligatorio · 中文需要拼音');try{const image_path=await upload($('#word-image').files[0],'vocabulary');const{error}=await db.from('vocabulary').insert({owner_id:user.id,term,language:lang,pronunciation:$('#word-pronunciation').value.trim(),pinyin,image_path});if(error)throw error;$('#word-form').classList.add('hidden');['word-term','word-pronunciation','word-pinyin'].forEach(id=>$('#'+id).value='');$('#word-image').value='';loadWords()}catch(e){toast(e.message)}};
async function loadWords(){if(!db||!user)return;const{data=[]}=await db.from('vocabulary').select('*,vocabulary_answers(*)').order('created_at',{ascending:false});const box=$('#word-list');box.innerHTML='';for(const w of data){const d=document.createElement('article');d.className='card item-card';const img=w.image_path?`<img src="${await signed(w.image_path)}" alt="${esc(w.term)}">`:'';const owner=profiles.find(p=>p.id===w.owner_id);const answers=(w.vocabulary_answers||[]).map(a=>`<div class="translation"><strong>${esc(profiles.find(p=>p.id===a.owner_id)?.display_name||'—')}</strong>: ${esc(a.translation)} ${a.pinyin?`· ${esc(a.pinyin)}`:''}</div>`).join('');d.innerHTML=`${img}<p class="eyebrow">${w.language==='zh'?'中文 · Chino':'ESPAÑOL · 西班牙语'}</p><h3>${esc(w.term)}</h3><p>${esc(w.pinyin||w.pronunciation||'')}</p><small>${esc(owner?.display_name||'—')}</small>${answers}<form class="translation answer"><input placeholder="Traducción · 翻译" required><input placeholder="Pinyin（如需要）"><button class="ghost">Añadir · 添加</button></form>`;d.querySelector('form').onsubmit=async e=>{e.preventDefault();const ins=e.target.querySelectorAll('input');await db.from('vocabulary_answers').upsert({vocabulary_id:w.id,owner_id:user.id,translation:ins[0].value,pinyin:ins[1].value},{onConflict:'vocabulary_id,owner_id'});loadWords()};box.append(d)}if(!data.length)box.innerHTML='<div class="card">La lista está vacía. · 词汇表还是空的。</div>'}
$('#new-resource').onclick=()=>$('#resource-form').classList.toggle('hidden');$('#save-resource').onclick=async()=>{const{error}=await db.from('resources').insert({owner_id:user.id,title:$('#resource-title').value.trim(),url:$('#resource-url').value.trim(),category:$('#resource-category').value,note:$('#resource-note').value.trim()});if(error)return toast(error.message);$('#resource-form').classList.add('hidden');loadResources()};
async function loadResources(){if(!db||!user)return;const{data=[]}=await db.from('resources').select('*').order('created_at',{ascending:false});$('#resource-list').innerHTML=data.map(r=>`<article class="card item-card"><p class="eyebrow">${esc(r.category)}</p><h3>${esc(r.title)}</h3><p>${esc(r.note||'')}</p><a href="${esc(r.url)}" target="_blank" rel="noopener">Abrir · 打开 ↗</a><div class="owner-actions"><small>${esc(profiles.find(p=>p.id===r.owner_id)?.display_name||'—')}</small>${r.owner_id===user.id?`<button class="danger resource-delete" data-id="${r.id}">Eliminar · 删除</button>`:''}</div></article>`).join('')||'<div class="card">Sin recursos todavía. · 还没有学习资源。</div>';$$('.resource-delete').forEach(b=>b.onclick=async()=>{await db.from('resources').delete().eq('id',b.dataset.id);loadResources()})}
async function loadStats(){if(!db||!user)return;const from=new Date();from.setDate(from.getDate()-13);const start=from.toISOString().slice(0,10),{data=[]}=await db.from('tasks').select('owner_id,task_date').gte('task_date',start);$('#stats').innerHTML=profiles.map(p=>{const dates=new Set(data.filter(x=>x.owner_id===p.id).map(x=>x.task_date)),pct=Math.round(dates.size/14*100);return `<article class="card stat-person"><div class="ring" style="--value:${pct}"><strong>${dates.size}/14</strong></div><div><h3>${esc(p.display_name)}</h3><p>${p.learning_language==='es'?'Español · 西班牙语':'中文 · Chino'}</p></div></article>`}).join('');const days=[...Array(14)].map((_,i)=>{const d=new Date(from);d.setDate(from.getDate()+i);return d.toISOString().slice(0,10)});$('#heatmap').innerHTML=days.map(d=>`<div class="day ${data.some(x=>x.task_date===d)?'on':''}" title="${d}">${d.slice(8)}</div>`).join('')}
document.addEventListener('DOMContentLoaded',boot);
